### ISSUE TITLE
Add descriptions on object properties

### ISSUE THREAD

**Issue by thomas4019** [thomas4019/expressa-admin#11]
These would be helpful to provide make schemas self documenting.

**Comment by coderofsalvation** [comment]
isn't this already supported?

```
{
  type:"object"
  properties{
    item_id:{
       type:"string",
       description:"this is a reference to the item collection",     
    }
  }
}
```

These are used in [json-editor](https://npmjs.org/package/json-editor) as well as the generated documentation of [expressa-swagger](https://www.npmjs.com/package/expressa-swagger) at `/api/doc`

**Comment by thomas4019** [comment]
You're right. It's actually an issue with my json-schema-editor not with expresssa-admin.
